/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as PoliticasRouteImport } from './routes/politicas'
import { Route as PortafoliosRouteImport } from './routes/portafolios'
import { Route as SolucionesRouteImport } from './routes/soluciones'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as CatalogoIndexRouteImport } from './routes/catalogo.index'
import { Route as CatalogoSlugRouteImport } from './routes/catalogo.$slug'
import { Route as PortafoliosIndexRouteImport } from './routes/portafolios.index'
import { Route as PortafoliosSlugRouteImport } from './routes/portafolios.$slug'
import { Route as SolucionesIndexRouteImport } from './routes/soluciones.index'
import { Route as SolucionesSlugRouteImport } from './routes/soluciones.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticasRoute = PoliticasRouteImport.update({
  id: '/politicas',
  path: '/politicas',
  getParentRoute: () => rootRouteImport,
} as any)
const PortafoliosRoute = PortafoliosRouteImport.update({
  id: '/portafolios',
  path: '/portafolios',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucionesRoute = SolucionesRouteImport.update({
  id: '/soluciones',
  path: '/soluciones',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CatalogoIndexRoute = CatalogoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CatalogoRoute,
} as any)
const CatalogoSlugRoute = CatalogoSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CatalogoRoute,
} as any)
const PortafoliosIndexRoute = PortafoliosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortafoliosRoute,
} as any)
const PortafoliosSlugRoute = PortafoliosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PortafoliosRoute,
} as any)
const SolucionesIndexRoute = SolucionesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SolucionesRoute,
} as any)
const SolucionesSlugRoute = SolucionesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SolucionesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/catalogo': typeof CatalogoRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/nosotros': typeof NosotrosRoute
  '/politicas': typeof PoliticasRoute
  '/portafolios': typeof PortafoliosRouteWithChildren
  '/soluciones': typeof SolucionesRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/catalogo/$slug': typeof CatalogoSlugRoute
  '/portafolios/$slug': typeof PortafoliosSlugRoute
  '/soluciones/$slug': typeof SolucionesSlugRoute
  '/catalogo/': typeof CatalogoIndexRoute
  '/portafolios/': typeof PortafoliosIndexRoute
  '/soluciones/': typeof SolucionesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contacto': typeof ContactoRoute
  '/nosotros': typeof NosotrosRoute
  '/politicas': typeof PoliticasRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/catalogo/$slug': typeof CatalogoSlugRoute
  '/portafolios/$slug': typeof PortafoliosSlugRoute
  '/soluciones/$slug': typeof SolucionesSlugRoute
  '/catalogo': typeof CatalogoIndexRoute
  '/portafolios': typeof PortafoliosIndexRoute
  '/soluciones': typeof SolucionesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/catalogo': typeof CatalogoRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/nosotros': typeof NosotrosRoute
  '/politicas': typeof PoliticasRoute
  '/portafolios': typeof PortafoliosRouteWithChildren
  '/soluciones': typeof SolucionesRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/catalogo/$slug': typeof CatalogoSlugRoute
  '/portafolios/$slug': typeof PortafoliosSlugRoute
  '/soluciones/$slug': typeof SolucionesSlugRoute
  '/catalogo/': typeof CatalogoIndexRoute
  '/portafolios/': typeof PortafoliosIndexRoute
  '/soluciones/': typeof SolucionesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/catalogo'
    | '/contacto'
    | '/nosotros'
    | '/politicas'
    | '/portafolios'
    | '/soluciones'
    | '/admin'
    | '/catalogo/$slug'
    | '/portafolios/$slug'
    | '/soluciones/$slug'
    | '/catalogo/'
    | '/portafolios/'
    | '/soluciones/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contacto'
    | '/nosotros'
    | '/politicas'
    | '/admin'
    | '/catalogo/$slug'
    | '/portafolios/$slug'
    | '/soluciones/$slug'
    | '/catalogo'
    | '/portafolios'
    | '/soluciones'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/catalogo'
    | '/contacto'
    | '/nosotros'
    | '/politicas'
    | '/portafolios'
    | '/soluciones'
    | '/_authenticated/admin'
    | '/catalogo/$slug'
    | '/portafolios/$slug'
    | '/soluciones/$slug'
    | '/catalogo/'
    | '/portafolios/'
    | '/soluciones/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CatalogoRoute: typeof CatalogoRouteWithChildren
  ContactoRoute: typeof ContactoRoute
  NosotrosRoute: typeof NosotrosRoute
  PoliticasRoute: typeof PoliticasRoute
  PortafoliosRoute: typeof PortafoliosRouteWithChildren
  SolucionesRoute: typeof SolucionesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politicas': {
      id: '/politicas'
      path: '/politicas'
      fullPath: '/politicas'
      preLoaderRoute: typeof PoliticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portafolios': {
      id: '/portafolios'
      path: '/portafolios'
      fullPath: '/portafolios'
      preLoaderRoute: typeof PortafoliosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soluciones': {
      id: '/soluciones'
      path: '/soluciones'
      fullPath: '/soluciones'
      preLoaderRoute: typeof SolucionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/catalogo/': {
      id: '/catalogo/'
      path: '/'
      fullPath: '/catalogo/'
      preLoaderRoute: typeof CatalogoIndexRouteImport
      parentRoute: typeof CatalogoRoute
    }
    '/catalogo/$slug': {
      id: '/catalogo/$slug'
      path: '/$slug'
      fullPath: '/catalogo/$slug'
      preLoaderRoute: typeof CatalogoSlugRouteImport
      parentRoute: typeof CatalogoRoute
    }
    '/portafolios/': {
      id: '/portafolios/'
      path: '/'
      fullPath: '/portafolios/'
      preLoaderRoute: typeof PortafoliosIndexRouteImport
      parentRoute: typeof PortafoliosRoute
    }
    '/portafolios/$slug': {
      id: '/portafolios/$slug'
      path: '/$slug'
      fullPath: '/portafolios/$slug'
      preLoaderRoute: typeof PortafoliosSlugRouteImport
      parentRoute: typeof PortafoliosRoute
    }
    '/soluciones/': {
      id: '/soluciones/'
      path: '/'
      fullPath: '/soluciones/'
      preLoaderRoute: typeof SolucionesIndexRouteImport
      parentRoute: typeof SolucionesRoute
    }
    '/soluciones/$slug': {
      id: '/soluciones/$slug'
      path: '/$slug'
      fullPath: '/soluciones/$slug'
      preLoaderRoute: typeof SolucionesSlugRouteImport
      parentRoute: typeof SolucionesRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CatalogoRouteChildren {
  CatalogoSlugRoute: typeof CatalogoSlugRoute
  CatalogoIndexRoute: typeof CatalogoIndexRoute
}

const CatalogoRouteChildren: CatalogoRouteChildren = {
  CatalogoSlugRoute: CatalogoSlugRoute,
  CatalogoIndexRoute: CatalogoIndexRoute,
}

const CatalogoRouteWithChildren = CatalogoRoute._addFileChildren(
  CatalogoRouteChildren,
)

interface PortafoliosRouteChildren {
  PortafoliosSlugRoute: typeof PortafoliosSlugRoute
  PortafoliosIndexRoute: typeof PortafoliosIndexRoute
}

const PortafoliosRouteChildren: PortafoliosRouteChildren = {
  PortafoliosSlugRoute: PortafoliosSlugRoute,
  PortafoliosIndexRoute: PortafoliosIndexRoute,
}

const PortafoliosRouteWithChildren = PortafoliosRoute._addFileChildren(
  PortafoliosRouteChildren,
)

interface SolucionesRouteChildren {
  SolucionesSlugRoute: typeof SolucionesSlugRoute
  SolucionesIndexRoute: typeof SolucionesIndexRoute
}

const SolucionesRouteChildren: SolucionesRouteChildren = {
  SolucionesSlugRoute: SolucionesSlugRoute,
  SolucionesIndexRoute: SolucionesIndexRoute,
}

const SolucionesRouteWithChildren = SolucionesRoute._addFileChildren(
  SolucionesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CatalogoRoute: CatalogoRouteWithChildren,
  ContactoRoute: ContactoRoute,
  NosotrosRoute: NosotrosRoute,
  PoliticasRoute: PoliticasRoute,
  PortafoliosRoute: PortafoliosRouteWithChildren,
  SolucionesRoute: SolucionesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
